<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Изменение-размерностей-массивов-с-помощью-[:,np.newaxis]-или-[:,None]" data-toc-modified-id="Изменение-размерностей-массивов-с-помощью-[:,np.newaxis]-или-[:,None]-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Изменение размерностей массивов с помощью <code>[:,np.newaxis]</code> или <code>[:,None]</code></a></span><ul class="toc-item"><li><span><a href="#Код-от-Мишки" data-toc-modified-id="Код-от-Мишки-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Код от Мишки</a></span></li><li><span><a href="#Тестируем-на-матрице-matrix-формой-3-×4" data-toc-modified-id="Тестируем-на-матрице-matrix-формой-3-×4-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Тестируем на матрице matrix формой 3 ×4</a></span></li></ul></li><li><span><a href="#Поэлементные-операции-между-массивами-и-совместимость-массивов" data-toc-modified-id="Поэлементные-операции-между-массивами-и-совместимость-массивов-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Поэлементные операции между массивами и совместимость массивов</a></span></li></ul></div>

# Изменение размерностей массивов с помощью `[:,np.newaxis]` или `[:,None]`

## Код от Мишки

In [1]:
import numpy as np
x = np.array([[2,5], [-3, 7]])

np.sum(x, axis=0)
# параметр axis=0 это значит, что мы суммируем по столбцам

array([-1, 12])

In [2]:
x

array([[ 2,  5],
       [-3,  7]])

In [3]:
# тут делим на суммы по столбцам
x/np.sum(x, axis=0)

array([[-2.        ,  0.41666667],
       [ 3.        ,  0.58333333]])

In [4]:
np.sum(x, axis=1)
# параметр axis=1 это значит, что мы суммируем по строкам

array([7, 4])

In [5]:
# то есть все прекрасно делится и в том случае, когда делим на суммы по строкам
#  потому что матрица 2 х 2.
x/np.sum(x, axis=1)

array([[ 0.28571429,  1.25      ],
       [-0.42857143,  1.75      ]])

In [6]:
np.sum(x, axis=1)[:, np.newaxis]

array([[7],
       [4]])

In [7]:
np.sum(x, axis=1)[:, np.newaxis].shape

(2, 1)

In [8]:
# [:, None] работает так же, как и  [:, np.newaxis]
np.sum(x, axis=1)[:,None] 

array([[7],
       [4]])

`[:, np.newaxis]` превращает список длины n в двумерный массив (матрицу) размера n x 1.

Фактически происходит следующее:
- `[:, ]` вот это показывает, что мы берем срез , куда включаем все элементы массива
- np.newaxis  - это добавление нового измерения


вместо `[:, np.newaxis]` можно использовать  `[:, None]` - тоже добавляет измерение

[разговор с ChatGPT про работу срезов [:,None] и [:,np.naxis]](https://chat.openai.com/share/56d37158-491f-4d2d-9f79-3ce252d07d36)

In [9]:
# Эта же операция [:,None] превращает двумерный массив в трехмерный
x[:, None].shape

(2, 1, 2)

## Тестируем на матрице matrix формой 3 &times;4

In [10]:
# x - это квадратная матрица. Там поэлентное стравнение всегда будет проходить, это неинтересно
# Попробуем матрицу 3 х 4
matrix = np.array([[ -10,  2,  13,  4], [ 5,  26,  -7,  8], [ 9, 10, 111, 12]])

In [11]:
matrix

array([[-10,   2,  13,   4],
       [  5,  26,  -7,   8],
       [  9,  10, 111,  12]])

In [12]:
# при axis=0 суммируем по столбцам. Было 4 столбца, значит в результате суммирования будет список из 4-х элементов
np.sum(matrix, axis=0)

array([  4,  38, 117,  24])

In [13]:
np.sum(matrix, axis=0)[:,None]

array([[  4],
       [ 38],
       [117],
       [ 24]])

In [14]:
np.sum(matrix, axis=0)[:,None].shape

(4, 1)

In [15]:
# при aqxis=1 суммируем по строкам . Было 3 строки, значит в результате суммирования будет список из 3-х элементов
np.sum(matrix, axis=1)

array([  9,  32, 142])

In [16]:
np.sum(matrix, axis=1)[:,None].shape

(3, 1)

In [17]:
matrix/(np.sum(matrix, axis=1)[:,None])

array([[-1.11111111,  0.22222222,  1.44444444,  0.44444444],
       [ 0.15625   ,  0.8125    , -0.21875   ,  0.25      ],
       [ 0.06338028,  0.07042254,  0.78169014,  0.08450704]])

In [18]:
matrix[:,None]

array([[[-10,   2,  13,   4]],

       [[  5,  26,  -7,   8]],

       [[  9,  10, 111,  12]]])

In [19]:
#   матрицу (двумерный массив) ингдикация превращает в трехмерный
matrix[:,None].shape

(3, 1, 4)

In [20]:
matrix[:,np.newaxis].shape

(3, 1, 4)

In [21]:
# а трехмерный массив индексация [:,None] превращает в четырехмерный
# всегда новое измерение добавляется во вторую позицию
test = matrix[:,None]
test[:,None].shape

(3, 1, 1, 4)

In [22]:
# проверим работу на трехмерном массиве
# radint - это функция, которая создает массив заданного размера со случайными целыми числами в заданном диапазоне. 
three_dimensional = np.random.randint(-10, 11, (3, 5, 4))
three_dimensional

array([[[  6,  -9,   1,   3],
        [  3, -10,   7,   7],
        [ -9,  -6,  -8,   6],
        [  0,  -2,  -8,   8],
        [  6,  -6, -10,   9]],

       [[  2,  -7,   6,  -6],
        [  8,   8,  -9,  -6],
        [ -5,   2,  -3,  -6],
        [ -8,  -2,   7,   9],
        [ -9,  -4,   8,  -8]],

       [[ -8,   1,   6,   3],
        [  6,   3,  -2,   5],
        [  4,  -6,   8,  -2],
        [  8,   7,  -6,  10],
        [  4, -10,  -2,  -5]]])

In [23]:
three_dimensional[:,None].shape
#тут видим, что новое измерение у нас добавляется всегда во вторую позицию. 
# И по этому добавленному измерению размер массива будет равен единице

(3, 1, 5, 4)

In [24]:
# а тут мы сделали индексацию два раза подряд, в результате у нас добавились ддва измерения - второе и третье
# и размер по каждому из этих измерений равыен единице
three_dimensional[:,None][:,None].shape

(3, 1, 1, 5, 4)

**Итого:**
- индексации `[:, np.newaxis]` и `[:,None]` работают одинаково
- `[:, None]` для любого массива дорбавляет новое измерение во вторую позицию
- по этому измерению размер получившегося массива будет равен единице
- То есть массив размера n<sub>1</sub> &times; n<sub>2</sub> &times;... &times; n<sub>k</sub> превращается в массив размера n<sub>1</sub> &times; 1 &times; n<sub>2</sub> &times;... &times; n<sub>k</sub>
- В частности, `[:, None]` превращает список длины n в двумерный массив (матрицу) размера n &times; 1.

Фактически происходит следующее:
- `[:, ]` вот это показывает, что мы берем срез , куда включаем все элементы массива
- `np.newaxis` или `None` - это добавление нового измерения

**Разговор с ChatGPT :**

[разговор с ChatGPT про работу срезов [:,None] и [:,np.naxis]](https://chat.openai.com/share/56d37158-491f-4d2d-9f79-3ce252d07d36)

# Поэлементные операции между массивами и совместимость массивов

**Поэлементные операции между массивами и совместимость массивов:**
- Поэлементные операции между массивами можно выполнеять тогда и только тогда, когда эти массивы совместимы в плане трансляции (broadcasting);
- Если два массива A и B имеют разное количество измерений, то перед выполнением поэлементной операции форма массива с меньшим количеством измерений дополняется единицами с левой стороны. Например, если одна матрица имеет форму `(5,4)`, а другая `(4,)`, то вторая матрица будет восприниматься как имеющая форму `(1,4)`.
- Массивы совместимы тогда и только тогда, когда **после** дополнения в каждом измерении размеры матриц А и В **или** совпадают **или** размер одной из этих матриц равен единице. То есть пусть у нас есть матрицы с одинаковым количестом измерений и разными размерами. Матрица А размером a<sub>1</sub> &times; a<sub>2</sub>&times;... &times; a<sub>n</sub> и матрица B размером b<sub>1</sub> &times; b<sub>2</sub>&times;... &times; b<sub>n</sub>. Между A и B **можно проводить поэлементные операции**, если для **$\forall i$ ((a<sub>i</sub> = b<sub>i</sub>) $\lor$ (min(a<sub>i</sub>, b<sub>i</sub>) = 1))**


[разговор с ChatGPT про совместимость массивов в плане трансляции для проведения поэлементных операций](https://chat.openai.com/share/403fcfae-85d5-411a-a7f4-363ab0228dcf)

**А теперь про поэлементные операции между матрицей и вектором:**

Что же происходит, когда мы делим матрицу (то есть массив размерности 2) на вектор?


В этом случае у нас естть массив m &times; n. Соответсвенно, мы можем проводить операцию с массивом с размером m &times; n, m &times; 1 или 1 &times; n.

Но поскольку вектор у нас имеет размерность один, то перед выполнением поэлдементной операции он дополняется единицей с левой стороны. То есть вектор длины k у нас превращается в матрицу размером  1 &times; k


**Вывод:**
Матрицу размера m &times; n мы можем умножать/делить и др только на вектор длины n


Если же у нас вектор длины m, то нам поможет ***операция индексации*** `[:,np.newaxis]` или `[:, None]` *(см. выше)*, которая добавит нам измерение во вторую позицию размером 1. То есть превратит наш вектор длины m в матрицу размера m &times; 1, в которой поэлементные операции прекрасно работают

**Следствие:**
- Если мы проводим операцию по столбцам матрице m &times; n, то у нас появляется вектор длины n. И между ним и исходной матрицей можно спокойно делать все поэлементные операции, потому что он автоматически дополнится единицами до матрицы 1 &times; n,
- Если мы проводим операцию по строкам в матрице m &times; n, то у нас появляется вектор длины m. И чтобы проводить поэлементные операции этого вектора и исходной матрицы, нам надо будет провести индексацию `[:, None]` 